# Generated by Django 4.1.1 on 2022-09-20 12:26

import cvsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0003_cvelement_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvelement',
            name='immagine',
            field=models.ImageField(blank=True, null=True),
        ),
    ]
