# Generated by Django 4.1.1 on 2022-10-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0006_lavori'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lavori',
        ),
    ]
