# Generated by Django 4.1.1 on 2022-10-05 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0007_delete_lavori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cucina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=100)),
                ('descrizione', models.CharField(default=None, max_length=60)),
                ('riassunto', models.CharField(default=None, max_length=500)),
                ('start', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('end', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
